In [15]:
import numpy as np
from sklearn import datasets
import pandas as pd
# from sklearn.model_selection import train_test_split

In [16]:
def train_test_split(x,y,test_size):
    test_size = 1 - test_size
    test_size = 100 *test_size
    arr_rand = np.random.rand(x.shape[0])
    split = arr_rand < np.percentile(arr_rand, test_size)
    x_train = x[split]
    y_train = y[split]
    x_test =  x[~split]
    y_test = y[~split]

#     print(len(x_train), len(y_train), len(x_test), len(y_test))
    return x_train, x_test, y_train, y_test
        

In [17]:
class Perceptron(object):
    def __init__(self):
        self.w = 0
    def fit(self,x_train,y_train):
        self.x_train = x_train
        self.y_train = y_train
        self.perceptron() # หา Vector W เพื่อใช้ในการคำนวณ matrix[W] trans X
    def perceptron(self):
        self.w =np.zeros((1,self.x_train.shape[1])) #สร้าง vector W ตามขนาดของ X-train (เพิ่มพื้นที่ของ bias แล้ว)
        while True: #ตามสูตรเลย
            m = 0 #miss
            for x, y in zip(self.x_train,self.y_train): #รวม x,y  train
                if np.dot(y, np.dot(self.w, x))<= 0:
                    self.w = self.w + (y * x)
                    m += 1
            if m == 0:
                break
        self.w = self.w.reshape(-1)
    def predict(self,x_test):
        preds = np.zeros((x_test.shape[0],1))
        for i in range(len(preds)):
            if np.matmul(np.array(self.w),x_test[i]) > 0:
                preds[i] = 1
            else:
                preds[i] = -1
        return preds.reshape(1,x_test.shape[0])[0]
    
    def score(self,x_test,y_test):
        count = 0
        pre = self.predict(x_test)
        for i in range(len(pre)):
            if pre[i] == y_test[i]:
                count+=1
        return count/len(y_test)

In [18]:
iris = datasets.load_iris()

In [19]:
y =iris.target

In [20]:
x = iris.data

In [21]:
x = np.hstack((np.ones(shape=(len(x),1)),x)) # adding column of 1 for bias term vec(x) = [x1,.....,xn,1]

In [22]:
y[y==0] = -1 #change classifier to binary classifier

In [23]:
y[(y==1) | (y==2)] = 1 #change classifier to binary classifier

In [24]:
x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size = 0.2)

In [25]:
p = Perceptron()

In [26]:
np.zeros((1,x_train.shape[1])) #test หา vector W

array([[0., 0., 0., 0., 0.]])

In [27]:
p.fit(x_train,y_train) #train

In [28]:
x_train[0]

array([1. , 5.1, 3.5, 1.4, 0.2])

In [29]:
x_test[0]

array([1. , 5.4, 3.7, 1.5, 0.2])

In [30]:
p.predict(x_test)

array([-1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [31]:
y_test

array([-1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [32]:
p.score(x_test,y_test)

1.0