In [446]:
from sklearn.datasets import load_boston
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt

In [447]:
print(load_boston()['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [448]:
class linear_regression:
    def __init__(self):
        self.w = np.zeros(2)
    def fit(self,x,y):
        # self.x = np.append(x.transpose(), np.ones((x.shape[1], 1)), axis=1)
        self.x = x
        self.y = y.reshape(-1,1)
    def getThetaClosedForm(self):
        Y = np.mat(self.y)
        firstPart = np.dot(self.x.T,self.x)
        secondPart = np.dot(self.x.T,Y)
        self.thetha = np.linalg.pinv(firstPart)*secondPart
        return self.thetha
    def predict(self):
        return np.dot(self.x,self.thetha)
    
        

## Set DATA

In [449]:
boston = load_boston()
x= boston.data
y = boston.target

In [457]:
data = load_boston()['data']
x_input = x

### DEAL WITH ALL DATA EXCEPT TARGET

In [456]:
x_in = np.concatenate([x_input, np.ones([np.shape(x_input)[0], 1])], axis=1)
x_in

array([[ 2.31 ,  6.575,  1.   ],
       [ 7.07 ,  6.421,  1.   ],
       [ 7.07 ,  7.185,  1.   ],
       ...,
       [11.93 ,  6.976,  1.   ],
       [11.93 ,  6.794,  1.   ],
       [11.93 ,  6.03 ,  1.   ]])

# USING LINEAR REGRESSION (ClOSED FORM)

In [452]:
closed = linear_regression()
closed.fit(x_in,y)
closed.getThetaClosedForm()

matrix([[-1.08011358e-01],
        [ 4.64204584e-02],
        [ 2.05586264e-02],
        [ 2.68673382e+00],
        [-1.77666112e+01],
        [ 3.80986521e+00],
        [ 6.92224640e-04],
        [-1.47556685e+00],
        [ 3.06049479e-01],
        [-1.23345939e-02],
        [-9.52747232e-01],
        [ 9.31168327e-03],
        [-5.24758378e-01],
        [ 3.64594884e+01]])

In [458]:
np.linalg.lstsq(x_in, y)

C:\Users\EMMIE\AppData\Local\Temp/ipykernel_12128/4132012522.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(x_in, y)


(array([ -0.33471389,   7.82205511, -22.89831573]),
 array([19807.614505]),
 3,
 array([318.75354429,  75.21961717,   2.10127199]))

## DEAL with two of the features: INDUS and RM

In [454]:
test = x_input = data[:,[2,5]]
closed.fit(test,y)
closed.getThetaClosedForm()

matrix([[-0.5151038 ],
        [ 4.53063061]])

In [455]:
np.linalg.lstsq(test, y)

C:\Users\EMMIE\AppData\Local\Temp/ipykernel_12128/4163066632.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(test, y)


(array([-0.5151038 ,  4.53063061]),
 array([22170.73271967]),
 2,
 array([318.11126552,  74.6019497 ]))