In [61]:
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split

## 1. read file

In [62]:
df = pd.read_csv("breast-cancer-wisconsin.csv")

## 2.replace null value(in this case "?")

In [63]:
df.replace("?", -9999 ,inplace = True)

## 3. make feature vector (vec(x))

-----
 - id ไม่เกี่ยวข้องกับ feature vector
 - class columns is label so we have to drop out on variables x but still has on it data

In [64]:
df.drop(['id'],1,inplace=True)

In [65]:
x = np.array(df.drop(['class'],1)) #put feature vector in other variables

In [66]:
y = np.array(df['class']) #put labels on y (y is answer)

In [67]:
x, y

(array([[5, 1, 1, ..., 3, 1, 1],
        [5, 4, 4, ..., 3, 2, 1],
        [3, 1, 1, ..., 3, 1, 1],
        ...,
        [5, 10, 10, ..., 8, 10, 2],
        [4, 8, 6, ..., 10, 6, 1],
        [4, 8, 8, ..., 10, 4, 1]], dtype=object),
 array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
        2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
        4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
        2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
        2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
        4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
        2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
        2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
        2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
        2, 4, 4, 4, 4, 2, 4,

## 4. split x and y for make traning set
----
- split x, y train and test from Data (pd)
- test_size is split ration between train and test
    - test_size = 0.2 data for train is 0.8

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2) #data for train 0.8

## 5. Train (learn function h from x_train, y_train

In [69]:
h = neighbors.KNeighborsClassifier(n_neighbors=7, p=2) #still empty can add (n_neighbors=?, p=?)

In [70]:
h.fit(x_train,y_train) #adjust h to fit (x_train,y_train) but in k-nn is only store

KNeighborsClassifier(n_neighbors=7)

In [71]:
x_train[0]

array([2, 1, 1, 1, 2, '1', 1, 1, 1], dtype=object)

## 6. predict

In [72]:
new_x = np.array([4,6,5,6,7,8,4,9,1])

In [73]:
result = h.predict(new_x.reshape(1,-1))

In [74]:
result

array([4], dtype=int64)

## 7.evaluate loss

In [75]:
h.score(x_test,y_test) #accuarcy 0.97 mean miss(100-97)%

0.9571428571428572